sudo: required

language: python

services:
  - docker

env:
  - PPM_TEST_S3_BUCKET=dbmi-ppm-test-output
  - PPM_TEST_OUTPUT_PATH=$TRAVIS_BUILD_DIR/ppm-test-output.tar.gz
  - PPM_TEST_TEST=test.PPMTestCase.test_neer_chrome

install:
  - cd $TRAVIS_BUILD_DIR
  - ./setup.sh

script:
  - ./test.sh

after_failure:
  - ./upload.sh