version: '2.1'
services:

  hypatio:
    volumes:
      - ./gunicorn-nginx-entry.override.sh:/entry_scripts/gunicorn-nginx-entry.override.sh
    entrypoint: ["/entry_scripts/gunicorn-nginx-entry.override.sh", "scireg", "/entry_scripts/gunicorn-nginx-entry.sh"]
    networks:
      ppm-test:
        aliases:
          - portal.aws.dbmi-dev.hms.harvard.edu
    environment:
      - APP_PORT=80
      - PS_PATH=secret.dbmi.hypatio.DEV
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
    healthcheck:
      test: curl --fail -s https://portal.aws.dbmi-dev.hms.harvard.edu:8005 || exit 1
      interval: 15s
      timeout: 5s
      retries: 15
    depends_on:
      scireg:
        condition: service_started
      sciauth:
        condition: service_started

  scireg:
    image: 685606823951.dkr.ecr.us-east-1.amazonaws.com/scireg:dev
    volumes:
      - ./gunicorn-nginx-entry.override.sh:/entry_scripts/gunicorn-nginx-entry.override.sh
    entrypoint: ["/entry_scripts/gunicorn-nginx-entry.override.sh", "scireg", "/entry_scripts/gunicorn-nginx-entry.sh"]
    networks:
      ppm-test:
        aliases:
          - registration.aws.dbmi-dev.hms.harvard.edu
    environment:
      - APP_PORT=8005
      - PS_PATH=secret.dbmi.scireg.DEV
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
    healthcheck:
      test: curl --fail -s https://registration.aws.dbmi-dev.hms.harvard.edu:8005 || exit 1
      interval: 15s
      timeout: 5s
      retries: 15

  sciauth:
    image: 685606823951.dkr.ecr.us-east-1.amazonaws.com/sciauth:dev
    volumes:
      - ./gunicorn-nginx-entry.override.sh:/entry_scripts/gunicorn-nginx-entry.override.sh
    entrypoint: ["/entry_scripts/gunicorn-nginx-entry.override.sh", "sciauth", "/entry_scripts/gunicorn-nginx-entry.sh"]
    networks:
      ppm-test:
        aliases:
          - authentication.aws.dbmi-dev.hms.harvard.edu
    environment:
      - APP_PORT=8001
      - PS_PATH=secret.dbmi.sciauth.DEV
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
    healthcheck:
      test: curl --fail -s https://authentication.aws.dbmi-dev.hms.harvard.edu:8001 || exit 1
      interval: 15s
      timeout: 5s
      retries: 15

  mail:
    image: mailhog/mailhog
    networks:
      ppm-test:
        aliases:
          - email-smtp.us-east-1.amazonaws.com
          - email.inbox.com

  stackdb:
    image: mysql:5.7
    volumes:
      - ./databases:/docker-entrypoint-initdb.d
      - ppm-test-db:/var/lib/mysql
    networks:
      ppm-test:
        aliases:
          - ppm-db.123456789012.us-east-1.rds.amazonaws.com
    environment:
      MYSQL_ROOT_PASSWORD: Q9ID8!2nkljadb@n5AEW9V
      MYSQL_DATABASE: stack
      MYSQL_USER: stack
      MYSQL_PASSWORD: Q9ID8!2nkljadb@n5AEW9V
    healthcheck:
      test: mysqladmin ping -uroot -pQ9ID8!2nkljadb@n5AEW9V
      interval: 15s
      timeout: 5s
      retries: 15

  hub:
    image: "dosel/zalenium"
    tty: true
    privileged: true
    volumes:
      - ppm-test-output:/home/seluser/videos
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      ppm-test:
        aliases:
          - hub.aws.dbmi.hms.harvard.edu
    ports:
      - "4444:4444"
    command: >
      start --desiredContainers 2
            --maxDockerSeleniumContainers 8
            --screenWidth 1024 --screenHeight 768
            --timeZone "America/New_York"
            --videoRecordingEnabled true
            --sauceLabsEnabled false
            --browserStackEnabled false
            --testingBotEnabled false
            --startTunnel false

  test:
    image: python:2.7
    volumes:
      - ./test-entrypoint.sh:/test-entrypoint.sh
      - ./tests:/tests
      - ./requirements.txt:/requirements.txt
      - ppm-test-output:/videos
    networks:
      - ppm-test
    environment:
      - PPM_TEST_TEST
      - PPM_TEST_ENVIRONMENT=docker
    entrypoint: /test-entrypoint.sh
    depends_on:
      hypatio:
        condition: service_started
      hub:
        condition: service_started
      mail:
        condition: service_started

networks:
  ppm-test:
    driver: bridge

volumes:
  ppm-test-db:
  ppm-test-output:
